# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CitiesRN' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CitiesRN

  

  platform :ios, '9.0'
  target 'CitiesRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CitiesRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CitiesRN-tvOS

  target 'CitiesRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
